name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on MacOS
    runs-on: macos-11
    env:
      UTM_VERSION: 0.12.0
      BOOST_VERSION: 1.84.0
      XERCES_C_VERSION: 3.2.5
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Build boost
        run: |
          mkdir -p build
          cd build
          curl -LO https://github.com/boostorg/boost/releases/download/boost-${BOOST_VERSION}/boost-${BOOST_VERSION}.tar.xz
          tar xf boost-${BOOST_VERSION}.tar.xz
          cd boost-${BOOST_VERSION}
          ./bootstrap.sh
          ./b2 -j4 --with-system --with-filesystem
          ./b2 install --prefix=$(pwd)/../../dist/boost
      - name: Build xerces-c
        run: |
          mkdir -p build
          cd build
          curl -LO https://downloads.apache.org/xerces/c/3/sources/xerces-c-${XERCES_C_VERSION}.tar.gz
          tar xzf xerces-c-${XERCES_C_VERSION}.tar.xz
          cd xerces-c-${XERCES_C_VERSION}
          ./configure --prefix=$(pwd)/../../dist/xerces-c
          make -j4
          make install
      - name: Build utm
        run: |
          mkdir -p build
          cd build
          git clone https://gitlab.cern.ch/cms-l1t-utm/utm.git -b utm_${UTM_VERSION}
          cd utm
          ./configure
          make all -j4 CPPFLAGS='-DNDEBUG -DSWIG' BOOST_BASE=$(pwd)/../../dist/boost XERCES_C_BASE=$(pwd)/../../dist/xerces-c
          make install PREFIX=$(pwd)/../../dist/utm
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: |
          export UTM_ROOT=$(pwd)/dist/utm
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${UTM_ROOT}/lib
          export DYLD_LIBRARY_PATH=${LD_LIBRARY_PATH}
          export UTM_XSD_DIR=${UTM_ROOT}
          export LC_ALL="en_US.UTF-8"
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos-utm-${UTM_VERSION}
          path: ./wheelhouse/*.whl
