name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on MacOS
    runs-on: macos-11
    env:
      UTM_VERSION: 0.12.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Install build dependecies
        run: |
          brew install -y boost xerces-c swig
      - name: Build utm ${UTM_VERSION}
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.9
          git clone https://gitlab.cern.ch/cms-l1t-utm/utm.git -b utm_${UTM_VERSION}
          cd utm
          ./configure
          make all -j4 CPPFLAGS='-DNDEBUG -DSWIG'
          make install PREFIX=$(pwd)/dist
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: |
          export UTM_ROOT=$(pwd)/utm/dist
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${UTM_ROOT}/lib
          export DYLD_LIBRARY_PATH=${LD_LIBRARY_PATH}
          export UTM_XSD_DIR=${UTM_ROOT}
          export LC_ALL="en_US.UTF-8"
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos-utm-${UTM_VERSION}
          path: ./wheelhouse/*.whl
