name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on MacOS
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Build boost
        run: bash .github/build_boost.sh
      - name: Build xerces-c
        run: bash .github/build_xerces_c.sh
      - name: Build utm
        run: bash .github/build_utm.sh
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: |
          BOOST_DIST=$(pwd)/dist/boost
          XERCES_C_DIST=$(pwd)/dist/xerces-c
          export UTM_ROOT=$(pwd)/dist/utm
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${UTM_ROOT}/lib:${BOOST_DIST}/lib:${XERCES_C_DIST}/lib}
          export DYLD_LIBRARY_PATH=${LD_LIBRARY_PATH}
          export UTM_XSD_DIR=${UTM_ROOT}
          export LC_ALL="en_US.UTF-8"
          export UTM_SKIP_VERSION_CHECK=true
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos
          path: ./wheelhouse/*.whl
