name: wheel

on: [push]

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    env:
      MODULE: tmEventSetup
      UTM_VERSION: 0.12.0
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependecies
      run: |
        sudo apt-get install -y libboost-dev libboost-system-dev libboost-filesystem-dev libxerces-c-dev swig
    - name: Build utm
      run: |
        curl -L https://gitlab.cern.ch/cms-l1t-utm/utm/-/archive/utm_${{ env.UTM_VERSION }}/utm-utm_${{ env.UTM_VERSION }}.tar.gz -O
        tar xzf utm-utm_${{ env.UTM_VERSION }}.tar.gz
        cd utm-utm_${{ env.UTM_VERSION }}
        ./configure
        make all -j4 CPPFLAGS='-DNDEBUG -DSWIG'
        make install PREFIX=.
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
    - name: Build wheel
      run: |
        export UTM_BASE="$(pwd)/utm-utm_${{ env.UTM_VERSION }}"
        python -m build --wheel
        python -m pip install dist/*-linux_x86_64.whl
    - name: Test module
      run: |
        export LD_LIBRARY_PATH="$(pwd)/utm-utm_${{ env.UTM_VERSION }}:$LD_LIBRARY_PATH"
        python -m ${{ env.MODULE }}.__init__
        python -c 'from ${{ env.MODULE }} import __version__; print(__version__)'
